### ISSUE TITLE
[Feat] organizations api connection

### ISSUE THREAD

**Issue by EASYhz** [Team-Notitime/NOFFICE-ANDROID#62]
## 🚀 About

> 이슈 관련 설명 또는 이슈 해결을 위한 목표와 방향을 작성해 주세요.
- organizations api 연결

## 📝 Details

> 상세 체크 리스트를 작성해 주세요.

- [x] 가입된 조직 페이징 조회
- [x] 조직 생성
- [x] 단일 조직 조회
- [x] 조직별 노티 페이징 조회
- [x] 조직 가입

## 📚 Remarks

> 공유할 내용 혹은 레퍼런스를 넣어주세요.
-

**Comment by easyhz** [comment]
- [x] 카테고리 조회
- [x] 이미지 업로드

**Comment by easyhz** [comment]
조직 가입 연결 필요합니다
